// carbon-angular-v10/src/app/features/tutorial/landing-page/landing-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ButtonType } from 'carbon-components-angular';

@Component({
  selector: 'app-landing-page',
  templateUrl: './landing-page.component.html',
  styleUrls: ['./landing-page.component.scss']
})
export class LandingPageComponent implements OnInit {

  learnMoreButtonType: ButtonType = "primary";

  constructor() { }

  ngOnInit(): void {
  }

}

<div ibmGrid class="bx--grid--full-width landing-page">
  <!-- First row: banner -->
  <div ibmRow class="landing-page__banner">
    <div ibmCol [columnNumbers]="{'lg': 16}">
      <ibm-breadcrumb [noTrailingSlash]="true" ariaLabel="Page navigation">
        <ibm-breadcrumb-item href="/"> Getting started </ibm-breadcrumb-item>
      </ibm-breadcrumb>
      <h1 class="landing-page__heading">Design &amp; build with Carbon</h1>
    </div>
  </div>
  <!-- Second row -->
  <div ibmRow class="landing-page__r2">
    <div ibmCol class="bx--no-gutter">
      <ibm-tabs ariaLabel="Tab navigation">
        <!-- About -->
        <ibm-tab heading="About">
          <div ibmGrid class="bx--grid--no-gutter bx--grid--full-width">
            <div ibmRow class="landing-page__tab-content">
              <div ibmCol [columnNumbers]="{'md': 4, 'lg': 7}">
                <h2 class="landing-page__subheading">
                  What is Carbon?
                </h2>
                <p class="landing-page__p">
                  Carbon is IBM’s open-source design system for digital
                  products and experiences. With the IBM Design Language
                  as its foundation, the system consists of working code,
                  design tools and resources, human interface guidelines,
                  and a vibrant community of contributors.
                </p>
                <button [ibmButton]="learnMoreButtonType">Learn more</button>
              </div>
              <div ibmCol class="bx--offset-lg-1" [columnNumbers]="{'md': 4, 'lg': 8}">
                <img
                class="landing-page__illo"
                src="../../../assets/tab-illo.png"
                alt="Carbon illustration"
                />
              </div>
            </div>
          </div>
        </ibm-tab>
        <!-- Design -->
        <ibm-tab heading="Design">
          <div ibmGrid class="bx--grid--no-gutter bx--grid--full-width">
            <div ibmRow class="landing-page__tab-content">
              <div ibmCol [columnNumbers]="{'lg': 16}">
                Rapidly build beautiful and accessible experiences. The Carbon kit
                contains all resources you need to get started.
              </div>
            </div>
          </div>
        </ibm-tab>
        <!-- Develop -->
        <ibm-tab heading="Develop">
          <div ibmGrid class="bx--grid--no-gutter bx--grid--full-width">
            <div ibmRow class="landing-page__tab-content">
              <div ibmCol [columnNumbers]="{'lg': 16}">
                Carbon provides styles and components in Vanilla, React, Angular,
                and Vue for anyone building on the web.
              </div>
            </div>
          </div>
        </ibm-tab>
        <!-- About -->
        <ibm-tab heading="Columns">
          <div ibmGrid class="bx--grid--no-gutter bx--grid--full-width">
            <div ibmRow class="landing-page__tab-content">
              <div ibmCol [columnNumbers]="{'lg': 16}">
                First:
                <ibm-code-snippet>
                  npm install --save --legacy-peer-deps apollo-angular@v1 apollo-angular-link-http apollo-cache-inmemory
                </ibm-code-snippet>
                Then:
                <ibm-code-snippet>
                  npm install --save apollo-client apollo-link graphql graphql-tag
                </ibm-code-snippet>
              </div>
            </div>
            <div ibmRow class="landing-page__banner">
              <div ibmCol [columnNumbers]="{'lg': 16}">1</div>
            </div>
            <div ibmRow class="landing-page__r2">
              <div ibmCol [columnNumbers]="{'md': 4, 'lg': 7}">7/16</div>
              <div ibmCol [columnNumbers]="{'md': 4, 'lg': 7}" class="bx--offset-lg-1">8/16</div>
            </div>
            <div ibmRow class="landing-page__r3">
              <div ibmCol [columnNumbers]="{'md': 4, 'lg': 4}">1/4</div>
              <div ibmCol [columnNumbers]="{'md': 4, 'lg': 4}">1/4</div>
              <div ibmCol [columnNumbers]="{'md': 4, 'lg': 4}">1/4</div>
              <div ibmCol [columnNumbers]="{'md': 4, 'lg': 4}">1/4</div>
            </div>
          </div>
        </ibm-tab>
      </ibm-tabs>
    </div>
  </div>
  <!-- Third row -->
  <app-info-section></app-info-section>
</div>

// carbon-react-v10/src/content/LandingPage/LandingPage.tsx
import { Breadcrumb, BreadcrumbItem, Button, Tab, Tabs } from "carbon-components-react";

const props = {
  tabs: {
    selected: 0,
    role: 'navigation',
  },
  tab: {
    role: 'presentation',
    tabIndex: 0,
  },
};

const LandingPage = () => {
  return (
    <div className="bx--grid bx--grid--full-width landing-page">
      <div className="bx--row landing-page__banner">
        <div className="bx--col-lg-16">
          <Breadcrumb noTrailingSlash aria-label="Page navigation">
            <BreadcrumbItem>
              <a href="/">Getting started</a>
            </BreadcrumbItem>
          </Breadcrumb>
          <h1 className="landing-page__heading">Design &amp; build with Carbon</h1>
        </div>
      </div>

      <div className="bx--row landing-page__r2">
        <div className="bx--col bx--no-gutter">
          <Tabs {...props.tabs} aria-label="Tab navigation">
            <Tab {...props.tab} label="About">
              <div className="bx--grid bx--grid--no-gutter bx--grid--full-width">
                <div className="bx--row landing-page__tab-content">
                  <div className="bx--col-md-4 bx--col-lg-7">
                    <h2 className="landing-page__subheading">
                      What is Carbon?
                    </h2>
                    <p className="landing-page__p">
                      Carbon is IBM’s open-source design system for digital
                      products and experiences. With the IBM Design Language
                      as its foundation, the system consists of working code,
                      design tools and resources, human interface guidelines,
                      and a vibrant community of contributors.
                    </p>
                    <Button>Learn more</Button>
                  </div>
                  <div className="bx--col-md-4 bx--offset-lg-1 bx--col-lg-8">
                    <img
                      className="landing-page__illo"
                      src={`${process.env.PUBLIC_URL}/tab-illo.png`}
                      alt="Carbon illustration"
                    />
                  </div>
                </div>
              </div>
            </Tab>
            <Tab {...props.tab} label="Design">
              <div className="bx--grid bx--grid--no-gutter bx--grid--full-width">
                <div className="bx--row landing-page__tab-content">
                  <div className="bx--col-lg-16">
                    Rapidly build beautiful and accessible experiences. The Carbon kit
                    contains all resources you need to get started.
                  </div>
                </div>
              </div>
            </Tab>
            <Tab {...props.tab} label="Develop">
              <div className="bx--grid bx--grid--no-gutter bx--grid--full-width">
                <div className="bx--row landing-page__tab-content">
                  <div className="bx--col-lg-16">
                    Carbon provides styles and components in Vanilla, React, Angular,
                    and Vue for anyone building on the web.
                  </div>
                </div>
              </div>
            </Tab>
          </Tabs>
        </div>
      </div>

      <div className="bx--row landing-page__r3">
        <div className="bx--col-md-4 bx--col-lg-4">
          <h3 className="landing-page__label">The Principles</h3>
        </div>
        <div className="bx--col-md-4 bx--col-lg-4">Carbon is Open</div>
        <div className="bx--col-md-4 bx--col-lg-4">Carbon is Modular</div>
        <div className="bx--col-md-4 bx--col-lg-4">Carbon is Consistent</div>
      </div>
    </div>
  );
};

export default LandingPage;
